package sketchpad.skylink.item.attributes

enum class ItemType(val reforgeable: Boolean) {
    MATERIAL(false),
    SWORD(true),
    PICKAXE(true),
    AXE(true),
    SHOVEL(true),
    HOE(true),
    SHEARS(true),
    HELMET(true),
    CHESTPLATE(true),
    LEGGINGS(true),
    BOOTS(true),
    ACCESSORY(true),
    WAND(true),
    BOW(true),
    GAUNTLET(true),
    DRILL(true),
    ARROW(true),
    TRAVEL_SCROLL(true),
    FISHING_ROD(true),
    FISHING_WEAPON(true),
    PET_ITEM(true),
    REFORGE_STONE(true),
    COSMETIC(true),
    LONGSWORD(true),
    CLOAK(true),
    BELT(true),
    GLOVES(true),
    NECKLACE(true),
    BRACELET(true),
    POWER_STONE(true),
    DEPLOYABLE(true),
    TROPHY_FISH(true),
}